Removing Version test

diff --git a/.github/workflows/liatriotests.yml b/.github/workflows/liatriotests.yml
--- a/.github/workflows/liatriotests.yml
+++ b/.github/workflows/liatriotests.yml
@@ -144,7 +144,7 @@ jobs:
         run: |
           docker push $DOCKER_REPO:latest
           docker push $DOCKER_REPO:${BRANCH_NAME}${NEW_VERSION}
-
+      # Argo CD Image Updater Takes care of this
       # - name: ⭐ Rename Container
       #   run: |
       #     echo "${NEW_VERSION}"
@@ -154,37 +154,38 @@ jobs:
       #     # sed -i -E "/name: NEW_VERSION/{n;s/value: \".*\"/value: \"$D_NEW_TAG\"/}" ArgoManifest/deployment.yaml
       #     sed -i "s|image: docker.io/${DOCKER_REPO}:.*|image: docker.io/${DOCKER_REPO}:${D_NEW_TAG}|" ArgoManifest/deployment.yaml
 
-      #
-      - name: ⭐ Update NEW_VERSION environment variable in deployment.yaml for Index.js. This does not affect the Image. Argo CD does that
-        run: |
-          D_NEW_TAG="${BRANCH_NAME}${NEW_VERSION}"
-          echo "$D_NEW_TAG"
-          # sed -i "/name: NEW_VERSION/{n;s/value:.*/value: \"$D_NEW_TAG\"/}" ArgoManifest/deployment.yaml
-          sed -i -E "/name: NEW_VERSION/{n;s/value: \".*\"/value: \"${D_NEW_TAG}\"/}" ArgoManifest/deployment.yaml
-          cat ArgoManifest/deployment.yaml
+      # Argo CD Image Updater Takes care of this
+      # - name: ⭐ Update NEW_VERSION environment variable in deployment.yaml for Index.js. This does not affect the Image. Argo CD does that
+      #   run: |
+      #     D_NEW_TAG="${BRANCH_NAME}${NEW_VERSION}"
+      #     echo "$D_NEW_TAG"
+      #     # sed -i "/name: NEW_VERSION/{n;s/value:.*/value: \"$D_NEW_TAG\"/}" ArgoManifest/deployment.yaml
+      #     sed -i -E "/name: NEW_VERSION/{n;s/value: \".*\"/value: \"${D_NEW_TAG}\"/}" ArgoManifest/deployment.yaml
+      #     cat ArgoManifest/deployment.yaml
 
-      - name: ⭐ Commit and Push deployment.yaml change
-        env:
-          GH_TOKEN: ${{ secrets.ARGO_ADD }}
-        run: |
-          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-            TARGET_BRANCH="${{ github.head_ref }}"
-          else
-            TARGET_BRANCH="${GITHUB_REF_NAME}"
-            echo "${TARGET_BRANCH}"
-          fi
-          git config user.name "github-actions[bot]"
-          git config user.email "1337@supa.com"
-          git checkout "$TARGET_BRANCH"
-          git add ArgoManifest/deployment.yaml
-          if git diff --cached --quiet; then
-            echo "✅ No changes to commit"
-          else
-            git commit -m "Automated update of deployment.yaml" #[skip ci]"
-            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
+      # Argo CD Image Updater Takes care of this
+      # - name: ⭐ Commit and Push deployment.yaml change
+      #   env:
+      #     GH_TOKEN: ${{ secrets.ARGO_ADD }}
+      #   run: |
+      #     if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+      #       TARGET_BRANCH="${{ github.head_ref }}"
+      #     else
+      #       TARGET_BRANCH="${GITHUB_REF_NAME}"
+      #       echo "${TARGET_BRANCH}"
+      #     fi
+      #     git config user.name "github-actions[bot]"
+      #     git config user.email "1337@supa.com"
+      #     git checkout "$TARGET_BRANCH"
+      #     git add ArgoManifest/deployment.yaml
+      #     if git diff --cached --quiet; then
+      #       echo "✅ No changes to commit"
+      #     else
+      #       git commit -m "Automated update of deployment.yaml" #[skip ci]"
+      #       git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
 
-            git push origin HEAD:$TARGET_BRANCH
-          fi
+      #       git push origin HEAD:$TARGET_BRANCH
+      #     fi
 
   GCloud:
     name: GCloud
@@ -314,7 +315,7 @@ jobs:
         run: |
           kubectl apply -f ArgoSetup/argo-app.yaml
 
-      - name: Argo Login # this may be an area to test
+      - name: Argo Login
         run: |
           kubectl rollout status deployment argocd-server -n argocd
           if ! lsof -i :8080 >/dev/null; then
@@ -340,6 +341,7 @@ jobs:
               sleep 10
             else
               echo "::add-mask::$EXTERNAL_IP"
+              echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
               break
             fi
           done
@@ -349,39 +351,37 @@ jobs:
             exit 1
           fi
 
-          echo "Curling app at http://$EXTERNAL_IP"
+      # This is disabled since version is not supported with Argo CD Image Update using Kustomize at this time 4/2/25
+      # - name: Verify Deployed Version
+      #   run: |
+      #     echo "Curling app"
 
-          RESPONSE=$(curl -s "http://$EXTERNAL_IP")
+      #       for attempt in {1..9}; do
 
-          echo "Full response: $RESPONSE"
+      #         RESPONSE=$(curl -s "http://$EXTERNAL_IP")
+      #         echo "Attempt $attempt to verify deployed version"
+      #         echo "Full response: $RESPONSE"
 
-          DEPLOYED_VERSION=""
-            for attempt in {1..9}; do
-              echo "Attempt $attempt to verify deployed version"
+      #         DEPLOYED_VERSION=$(echo "$RESPONSE" | jq -r '.version // .NEW_VERSION // empty')
 
-              RESPONSE=$(curl -s "http://$EXTERNAL_IP")
-              echo "Full response: $RESPONSE"
+      #         echo "Comparing expected version ${BRANCH_NAME}${NEW_VERSION} to deployed version ${DEPLOYED_VERSION}"
 
-              DEPLOYED_VERSION=$(echo "$RESPONSE" | jq -r '.version // .NEW_VERSION // empty')
+      #         if [[ "$DEPLOYED_VERSION" == "${BRANCH_NAME}${NEW_VERSION}" ]]; then
+      #           echo "✅ Version match confirmed: $DEPLOYED_VERSION"
+      #           break
+      #         fi
 
-              echo "Comparing expected version ${BRANCH_NAME}${NEW_VERSION} to deployed version ${DEPLOYED_VERSION}"
+      #         echo "❌ Version mismatch (Attempt $attempt). Retrying in 10 seconds"
+      #         sleep 10
+      #       done
 
-              if [[ "$DEPLOYED_VERSION" == "${BRANCH_NAME}${NEW_VERSION}" ]]; then
-                echo "✅ Version match confirmed: $DEPLOYED_VERSION"
-                break
-              fi
-
-              echo "❌ Version mismatch (Attempt $attempt). Retrying in 10 seconds"
-              sleep 10
-            done
-
-            # Final check after retries
-            if [[ "$DEPLOYED_VERSION" != "${BRANCH_NAME}${NEW_VERSION}" ]]; then
-              echo "❌ Final mismatch after retries!"
-              echo "Expected: ${BRANCH_NAME}${NEW_VERSION}"
-              echo "Got:      $DEPLOYED_VERSION"
-              exit 1
-            fi
+      #       # Final check after retries
+      #       if [[ "$DEPLOYED_VERSION" != "${BRANCH_NAME}${NEW_VERSION}" ]]; then
+      #         echo "❌ Final mismatch after retries!"
+      #         echo "Expected: ${BRANCH_NAME}${NEW_VERSION}"
+      #         echo "Got:      $DEPLOYED_VERSION"
+      #         exit 1
+      #       fi
 
       - name: Change-Cause for New Deployment (Shown in Tests)
         run: |
