Update liatriotests.yml
Moving HPA Test forward so that it may spin down a bit before the rollout

diff --git a/.github/workflows/liatriotests.yml b/.github/workflows/liatriotests.yml
--- a/.github/workflows/liatriotests.yml
+++ b/.github/workflows/liatriotests.yml
@@ -312,6 +312,45 @@ jobs:
         run: |
           kubectl apply -f k8s/namespaces.yaml
 
+      - name: ⭐ Horizontal Pod Autoscaler To 1% to Trigger All Pods
+        run: |
+          echo "Patching HPA - This should not trigger a rollout"
+          kubectl patch hpa liatrio-hpa-api -n $DEPLOY_ENV --patch-file k8s/hpa_test.yaml
+          echo ""
+          echo "Horizontal Pod Autoscaler Status. Note: CPU may be unknown as that can take a bit to load after a patch. HPA:"
+          kubectl get hpa -n $DEPLOY_ENV
+          echo ""
+          echo "Current Pods:"
+          kubectl get pods -n $DEPLOY_ENV
+
+      - name: Wait for HPA to scale
+        run: |
+          HPA_NAME=liatrio-hpa-api
+          MAX_REPLICAS=$(kubectl get hpa $HPA_NAME -n $DEPLOY_ENV -o jsonpath='{.spec.maxReplicas}')
+          echo "Waiting for $HPA_NAME to scale to $MAX_REPLICAS replicas..."
+
+          for i in {1..20}; do
+            CURRENT_REPLICAS=$(kubectl get deployment liatrio-deployment-api -n $DEPLOY_ENV -o jsonpath='{.status.readyReplicas}')
+            echo "Ready replicas: $CURRENT_REPLICAS"
+
+            if [[ "$CURRENT_REPLICAS" == "$MAX_REPLICAS" ]]; then
+              echo "$HPA_NAME has reached max replicas ($MAX_REPLICAS)"
+              break
+            fi
+
+            echo "Waiting... ($i/20)"
+            sleep 15
+          done
+
+          if [[ "$CURRENT_REPLICAS" != "$MAX_REPLICAS" ]]; then
+            echo "Timeout: $HPA_NAME did not reach max replicas."
+            exit 1
+          fi
+
+      - name: Setting HPA back to normal
+        run: |
+          kubectl patch hpa liatrio-hpa-api -n $DEPLOY_ENV --patch-file k8s/hpa_reset.yaml
+
       - name: ⭐ RBAC. Role Based Action Control. Create Service Account, Roles, & Binding
         run: |
           echo "Setting up Service Account: github-actions-sa-user to have get & list for namespaces, pods, services, & deployments"      
@@ -360,45 +399,6 @@ jobs:
           echo ""
           echo "Rollout History:"
           kubectl rollout history deployment liatrio-deployment-api -n $DEPLOY_ENV
-
-      - name: ⭐ Horizontal Pod Autoscaler To 1% to Trigger All Pods
-        run: |
-          echo "Patching HPA - This should not trigger a rollout"
-          kubectl patch hpa liatrio-hpa-api -n $DEPLOY_ENV --patch-file k8s/hpa_test.yaml
-          echo ""
-          echo "Horizontal Pod Autoscaler Status. Note: CPU may be unknown as that can take a bit to load after a patch. HPA:"
-          kubectl get hpa -n $DEPLOY_ENV
-          echo ""
-          echo "Current Pods:"
-          kubectl get pods -n $DEPLOY_ENV
-
-      - name: Wait for HPA to scale
-        run: |
-          HPA_NAME=liatrio-hpa-api
-          MAX_REPLICAS=$(kubectl get hpa $HPA_NAME -n $DEPLOY_ENV -o jsonpath='{.spec.maxReplicas}')
-          echo "Waiting for $HPA_NAME to scale to $MAX_REPLICAS replicas..."
-
-          for i in {1..20}; do
-            CURRENT_REPLICAS=$(kubectl get deployment liatrio-deployment-api -n $DEPLOY_ENV -o jsonpath='{.status.readyReplicas}')
-            echo "Ready replicas: $CURRENT_REPLICAS"
-
-            if [[ "$CURRENT_REPLICAS" == "$MAX_REPLICAS" ]]; then
-              echo "$HPA_NAME has reached max replicas ($MAX_REPLICAS)"
-              break
-            fi
-
-            echo "Waiting... ($i/20)"
-            sleep 15
-          done
-
-          if [[ "$CURRENT_REPLICAS" != "$MAX_REPLICAS" ]]; then
-            echo "Timeout: $HPA_NAME did not reach max replicas."
-            exit 1
-          fi
-
-      - name: Setting HPA back to normal
-        run: |
-          kubectl patch hpa liatrio-hpa-api -n $DEPLOY_ENV --patch-file k8s/hpa_reset.yaml
 
       - name: ⭐ Patch Rollout
         run: |
